### ISSUE TITLE
Wowza playlist is not working

### ISSUE THREAD

**Issue by yogeshbelur** [WowzaMediaSystems/wse-plugin-streampublisher#1]
i have following scenario and i want to know how to achieve

in vod i have transcoded videos and corresponding smil file

when i play the individual smil files, playback is successful.

but i do create a playlist and play, its failing

```
<?xml version="1.0" encoding="UTF-8"?><smil>
<head>
</head>
<body>
<stream name="Stream1"></stream>
<playlist name="pl1" playOnStream="Stream1" repeat="true" scheduled="2016-04-15 16:00:00">
<video src="smil:video_3/bb3.smil" start="0" length="300"/>
<video src="smil:video_4/bb4.smil" start="0" length="300"/>
<video src="smil:video_5/bb5.smil" start="0" length="300"/>
</playlist>
</body>
</smil>
```

**Error:**
404 not found when inspect the network call

**Comment by rogerlittin** [comment]
Hi,

The video sources must each be the name of a single video file or a live stream.  They cannot be other smil files.

If you are wanting to create Adaptive Bitrate Streams using the Stream Publisher then you would need to create a separate publisher stream for each rendition.  See the following guide for details:

https://www.wowza.com/forums/content.php?224-How-to-do-scheduled-adaptive-bitrate-streaming-using-Stream-class-streams.

This method works best with schedules that only contain video files and no live sources. The separate publishers  aren't synchronized, so playback issues can occur if their sources are in exact alignment.  An alternative would be to create a single publisher stream and then use the Wowza Transcoder to create an Adaptive Bitrate Stream from that.
