### ISSUE TITLE
Calculate timeshift for a scheduled media

### ISSUE THREAD

**Issue by mrlika** [WowzaMediaSystems/wse-plugin-streampublisher#2]
Hi,

My `streamschedule.smil` looks like this:

```xml
<stream name="ch1-360"></stream>
<playlist name="ch1-360-1" playOnStream="ch1-360" scheduled="2019-11-20 14:00:00">
    <video src="mp4:video.mp4" start="60" length="-1" />
</playlist>
```

It means that at `14:00` I want the plugin to play 60th second of `video.mp4` video. And at `14:01` I want the plugin to play 120th second of the video.

It is true only if I start a Wowza app before 14:00. But if I start/restart the app at 14:01 (or run API call to update the schedule) the plugin starts to play the video again from 60th second and not from 120th second.

Is it possible to calculate the actual start taking into account the difference between a scheduled time and current time?

**Comment by rogerlittin** [comment]
Hi,

This would not be possible without modifying how the playlist schedule is created and parsed.  As it is at the present time, the playlist will be started _at_ or _after_ the time specified in the _scheduled_ parameter. There is nothing that determines the difference between the current time and the scheduled time.  Also, what you are proposing may work as long as the time difference is less than the video duration but if it is longer, then there could be issues with how the seek is handled.

I would suggest starting with the current implementation and modifying it to suit what you want to do.

Regards,

Roger.
